bkui-vue2-helper/attributes.json
bkui-vue2-helper/tags.json
package.json

在 VSCode 中支持 Vetur 对组件进行属性和标签提示

chore:support vetur intelilSence

---

example/components/dropdown-menu/readme.md
src/components/dropdown-menu/dropdown-menu.vue
src/components/tree/tree.vue
src/ui/dropdown-menu.css

dropdown-menu 下面框，支持position-fixed配置
tree 设置拖拽，拖拽的时候，鼠标形状修改

feature(dropdown-menu): 下拉框增加position-fixed属性支持。【tree】拖曳时候，鼠标样式去掉绿色加号

---

src/components/slider/slider-button.vue

minor: 滑动选择器滑动结束时应该删除绑定的事件

---

example/components/changelog/readme.md
package.json

feat: bump to 2.3.5

---

package.json

feat: bump to 2.3.6-beta.1

---

example/components.config.js
example/components/directives/readme.md
example/components/spin/readme.md
example/router.js
src/components/spin/index.js
src/components/spin/spin.vue
src/directives/copy.js
src/index.js
src/ui/bk.css
src/ui/spin.css

- 增加spin组件，用于展示loading状态
- 复制指令，实现复制文本

feature: 增加spin组件和复制指令

---

example/components/table/readme.md
src/components/table/table-body.js
src/components/table/table-layout.js
src/components/table/table.vue
src/components/virtual-render/index.js
src/components/virtual-render/v-virtual-render.js
src/components/virtual-render/virtual-render.js
src/ui/virtual-render.css

feature: [Table] 添加内置虚拟滚动

---

src/ui/cascade.css
src/ui/color-picker.css
src/ui/input.css
src/ui/search-select.css
src/ui/select.css
src/ui/upload.css

bugfix: 修复表单组件背景色

---

example/components/dialog/example.vue
src/components/tab/tab.vue
src/ui/tab.css

- bugfix: 组件tab一开始下划线没有，点击后才出现 #23

bugfix: 组件tab一开始下划线没有，点击后才出现 #23

---

example/components/changelog/readme.md
example/components/directives/readme.md
gulpfile.component.js
package.json

feat: bump to 2.3.6

---

src/components/table/table-column.js
src/components/table/table-header.js
src/components/table/table-layout.js
src/components/table/table-store.js

perf: table-column 宽度计算

---

src/components/table/table-layout.js

bugfix: table column 为空时报错

---

example/components/color/readme.md
example/css/app.css

feat: [color]-增加了蓝色和灰色

---

example/components/changelog/readme.md
example/components/dialog/example.vue
example/components/info-box/example.vue
example/components/info-box/readme.md
package.json
src/components/dialog/dialog.vue
src/ui/dialog.css

- chore: info 样式优化；dialog 问题修复

chore: info 样式优化；dialog 问题修复

---

example/components/divider/readme.md

bugfix: divider 文档修复

---

example/components/changelog/readme.md
example/components/tag-input/readme.md
package.json
src/components/tag-input/tag-input.vue

feat: bump to 2.3.7

---

example/components/changelog/readme.md
example/components/tab/readme.md
package.json

- feat: bump to 2.3.8-beta.1 #83

feat: bump to 2.3.8-beta.1

---

src/ui/tab.css

bugfix: [tab] border-card嵌入unborder-card样式问题 #85

---

example/components/tag-input/readme.md

bugfix: tag-input 文档问题

---

src/components/virtual-scroll/virtual-scroll.vue

feat: [virtual-scroll] 优化虚拟滚动折叠展开逻辑 #58 (#58)

feat: [virtual-scroll] 优化虚拟滚动折叠展开逻辑 #58 (#58)

---

build/config.js
example/components/changelog/readme.md
package.json

feat: bump to 2.3.8

---

example/components/progress/readme.md
src/components/progress/progress.vue

feat: (progress)组件添加fixed小数点位数配置

---

example/components/notify/readme.md
src/components/notify/notify.vue

feat: [notify]组件支持html渲染message的方式
- Fixes #137

feat: [notify]组件支持html渲染message的方式

---

example/components/changelog/readme.md
package.json

feat: bump to 2.3.10

---

example/components/table/readme.md
src/components/popover/popover.vue
src/components/select/select.vue
src/components/table/table-store.js
src/components/table/table.vue
src/mixins/z-index.js
src/ui/table.css

- table增加底部滚动加载效果
- 修复select zIndex设置不生效问题

feature: table增加底部滚动加载效果以及修复select zIndex设置不生效问题

---

example/components/big-tree/readme.md
src/components/big-tree/tree.vue
src/ui/big-tree.css

feature(big-tree): 增加 size 选项

---

example/components/date-picker/example.vue
example/components/date-picker/readme.md
src/components/date-picker/panel/date-range.vue
src/components/date-picker/picker.vue
src/components/loading/loading.vue

- DatePicker
- Fixes # [issues](https://github.com/TencentBlueKing/bkui-vue2/issues/173)

feature: DatePicker组件新增快捷选项区域插槽

---

example/components/breadcrumb/readme.md
example/components/cascade/readme.md
src/components/breadcrumb/breadcrumb.vue
src/components/cascade/cascade.vue
src/components/table/table-column.js
src/components/table/table-layout.js
src/components/table/table.vue
src/ui/breadcrumb.css
src/ui/cascade.css

feature: 面包屑增加返回功能以及前置插槽
bugfix: 修复table组件在dialog中高度失效问题
bugfix: 修复table组件开启tooltip后快速滚动列表tooltip不能及时消失的问题
bugfix: 修复级联菜单多选情况下动态加载bug
bugfix: 修复级联菜单宽度小时，tag上删除按钮样式错乱

feature: bugfix

---

example/components/changelog/readme.md
package.json
src/ui/table.css

feat: bump to 2.4.0

---

example/components/spin/readme.md
example/components/table/readme.md
src/components/table/table.vue
src/ui/spin.css
src/ui/table.css

feature:table底部加载样式调整，spin组件新增info主题

feature:table底部加载样式调整，spin组件新增info主题

---

example/components/changelog/readme.md
package.json
src/components/date-picker/panel/date-range.vue
src/components/date-picker/panel/date.vue
src/components/table/table.vue
src/ui/table.css

feat: bump to 2.4.1-beta.2

---

src/components/checkbox/checkbox-group.vue
src/components/checkbox/checkbox.vue

optimization: 更改checkbox-group注册子组件方式

---

example/components/changelog/readme.md
package.json
src/components/pagination/pagination.vue

feat: bump to 2.4.1

---

example/components/directives/readme.md
package.json
src/components/checkbox/checkbox.vue
src/components/image/image.vue
src/components/loading/loading.vue

feat: bump to 2.4.2

---

example/components/changelog/readme.md
package.json
src/components/tab/tab.vue
src/components/table/table-layout.js

feat: bump to 2.4.3

---

example/components/changelog/readme.md
package.json
src/components/loading/loading.vue

feat: bump to 2.4.4

---

example/components/select/readme.md
example/components/table/readme.md
example/components/upload/readme.md
example/css/app.css
package.json
src/components/cascade/cascade.vue
src/components/select/select.vue
src/components/table/table-layout.js
src/components/table/table.vue
src/components/upload/request.js
src/components/upload/upload.vue
src/ui/table.css

feature: select组件增加下拉框高度在标签多选形式是否自动撑开配置 && 增加远程搜索样例
feature: upload组件支持大文件分片上传
bugfix: cascade组件修复禁用状态下依旧能删除tag的问题
bugfix: table组件修复开启定位和自动行高拖动修改列宽，影响行高没有重新计算定位行高问题

feature: select组件和upload组件增加新特性已经修复cascade组件和table组件bug

---

src/ui/pagination.css
src/ui/table.css

bugfix: [table]修复表格会被外部white-space样式影响问题

---

example/components/badge/readme.md
example/components/big-tree/readme.md
example/components/changelog/readme.md
package.json
src/components/cascade/cascade.vue

feat: bump to 2.4.6

---

example/components/button/readme.md
example/components/select/readme.md
src/components/button/button.vue
src/components/select/select.vue
src/ui/button.css
src/ui/select.css

- 修复button组件text状态loading状态bug; 
- 下来列表组件（select）支持滚动分页；

修复button组件text状态loading状态bug && 下来列表组件（select）支持滚动分页

---

example/components/changelog/readme.md
example/components/dropdown-menu/example.vue
example/components/select/readme.md
example/router.js
package.json
src/components/dropdown-menu/dropdown-menu.vue
src/ui/dropdown-menu.css

feat: bump to 2.4.7

---

example/components/slider/example.vue
example/router.js
package.json
src/components/slider/slider-button.vue
src/components/slider/slider.vue

- bugfix: slider min-value 设置为负值时无法正确渲染的问题 issue #231

bugfix: slider min-value 设置为负值时无法正确渲染的问题 issue #231

---

package.json
src/components/date-picker/picker.vue

- feat: 修复 timer-picker 弹框偶发不会关闭的问题

feat: 修复 timer-picker 弹框偶发不会关闭的问题

---

example/components/changelog/readme.md
example/components/color/readme.md
example/components/date-picker/readme.md
example/components/info-box/readme.md
example/css/app.css
package.json
src/components/date-picker/panel/time-range.vue
src/components/date-picker/panel/time.vue
src/components/date-picker/picker.vue
src/components/info-box/info-box.js
src/directives/clickoutside.js

feat: bump to 2.4.8

---

example/components/image/readme.md
src/components/image-viewer/image-viewer.vue
src/components/image/image.vue
src/components/zoom-image/zoom-image.vue

Image，ZoomImage组件图片被遮盖
249
- Fixes #

修复Image，ZoomImage组件被遮盖问题

---

example/components/table/readme.md
src/components/table/table.vue

feature: [Table]翻页事件，传递当前页和每页条数

feature: [Table]翻页事件，传递当前页和每页条数

---

src/components/loading/directive.js
src/components/tab/tab.vue

loading指令出现el.viewmodel.$mount读取错误 #258

---

example/components/pagination/readme.md
src/components/pagination/pagination.vue
src/ui/pagination.css
src/ui/select.css

feature: 支持分页跳转和调整下来选框禁用时箭头颜色

---

bkui-vue2-helper/attributes.json
bkui-vue2-helper/tags.json
build/config.js
example/components/info-box/readme.md
src/components/dialog/dialog.vue

feature(info): 支持info组件关闭icon自定义

---

bkui-vue2-helper/attributes.json
bkui-vue2-helper/tags.json
build/config.js
example/components/info-box/readme.md
example/components/tab/readme.md
src/components/dialog/dialog.vue
src/components/tab/tab.vue
src/ui/tab.css

feature(tab): 支持新增按钮前添加自定义插槽内容和支持info组件关闭icon自定义

---

example/components/select/readme.md
src/components/select/select-tag.vue
src/components/select/select.vue
src/ui/select.css

feat: select组件tag多选模式支持allow create

---

example/components/select/readme.md
src/components/select/select.vue

select组件
在输入框输入关键词后，按下enter，确定搜索结构
可以配置 allow-enter 值为false，禁用这一功能

feat:[select]根据搜索结果确定选择值 #273

---

example/components/changelog/readme.md
example/components/input/example.vue
example/components/radio/example.vue
example/components/switcher/readme.md
package.json
src/components/divider/divider.vue
src/components/input/input.vue
src/components/radio/radio-group.vue
src/components/switcher/switcher.vue
src/ui/divider.css

feat: bump to 2.4.10

---

example/components/swiper/readme.md
src/components/swiper/swiper.vue

feat:[swiper] 修改swiper高宽规则

---

example/components/changelog/readme.md
package.json

feat: bump to 2.4.11

---

src/components/input/input.vue

bugfix(input): 修复type为number时数字键盘输入不生效问题 #287

---

example/components/search-select/readme.md
src/components/search-select/search-select.vue

feat: search-select组件支持失焦清空输入框内容

---

example/components/select/readme.md
src/components/select/select.vue

- 下拉框组件选型数量如果超过一定（默认0个）显示搜索框，用于解决只有少数选型，依然显示搜索框

feature(select): 下拉框组件选型数量如果超过一定（默认0个）显示搜索框

---

example/components/slider/readme.md
src/components/slider/slider.vue

feature: 修复min-value max-value输入框问题，如min-value为5，想输入11，结果马上变成5

feature: 修复slider min-value max-value输入框问题

---

example/components/select/readme.md
example/components/table/readme.md

bk-table组件virtual-render属性配置说明补充 && select id-key文档调整

feature: bk-table组件virtual-render属性配置说明补充 && select id-key文档调整

---

example/App.vue
example/components/changelog/readme.md
example/components/input/example.vue
example/components/search-select/example.vue
example/components/select/example.vue
example/components/table/example.vue
package.json
src/components/table/table.vue
src/ui/popover.css
src/ui/tab.css
test.html

feat: bump to 2.4.12

---

example/components/transfer/readme.md
src/components/transfer/transfer.vue
src/ui/transfer.css

- Transfer穿梭框组件支持设置disabled状态
- 修复Transfer穿梭框组件设置排序不生效bug

feature: Transfer穿梭框组件支持设置disabled状态和修复Transfer穿梭框组件设置排序不生效bug

---

src/components/select/option-group.vue

bugfix: select 分组选中状态

---

example/components/table/readme.md
src/components/table/table.vue
src/ui/table.css

feat(table): 添加深色表头、自定义表头配色等属性

---

example/components/changelog/readme.md
example/components/date-picker/example.vue
example/components/date-picker/readme.md
example/components/dropdown-menu/readme.md
example/components/input/example.vue
example/components/time-picker/example.vue
example/components/time-picker/readme.md
package.json
src/components/date-picker/base/time-spinner.vue
src/components/date-picker/panel/time.vue
src/components/input/input.vue
src/locale/lang/en-US.js
src/locale/lang/zh-CN.js
src/ui/dialog.css
src/ui/dropdown-menu.css
src/ui/sideslider.css
src/ui/time-picker.css

feat: 优化部分组件样式

---

example/components/popconfirm/readme.md
src/components/popconfirm/popconfirm.vue
src/ui/popconfirm.css

- feat(popconfirm): 设计规范更新
- Fixes #

feat(popconfirm): 设计规范更新

---

example/components/table/readme.md
src/ui/table.css

feat(table): 添加自定义表头文档示例

---

src/directives/tooltips.js

perf: tooltips配置

---

example/components/changelog/readme.md
package.json

- feat: change vue version to 2.7.x

feat: change vue version to 2.7.x

---

example/components/table/readme.md

bugfix(table): table例子优化 & 走查修复

---

src/components/pagination/small-jump.vue

bugfix: 小型分页器，页码跳转限制输入整数

---

src/components/sideslider/sideslider.vue

- bugfix: Sideslider侧栏销毁后删除dom节点

bugfix: Sideslider侧栏销毁后删除dom节点

---

example/components/navigation/demo1.vue
example/components/navigation/readme.md
example/router.js
src/components/navigation/navigation-menu-item.vue
src/components/navigation/navigation-menu.vue
src/ui/navigation.css

feat(navigation): 导航组件样式优化

---

src/components/card/card.vue

feature: card组件修改展开动画时间

---

package.json

feat: bump to 2.4.15-beta.4

---

package.json
src/components/tag/tag.vue

- feature: [bk-tag] 抛出click事件，允许在组件上支持监听click事件 && bump to 2.4.15-beta.6

feature: [bk-tag] 抛出click事件，允许在组件上支持监听click事件 && bump to 2.4.15-beta.6

---

example/components/cascade/readme.md
src/components/cascade/cascade.vue
src/components/cascade/caspanel.vue

bugfix: [cascade] 级联选框，当层级过多宽度超过其上方的下拉框时，展示错误 #293

---

example/components/changelog/readme.md
package.json
src/ui/dropdown-menu.css

feat: bump to 2.5.1

---

package.json
src/directives/tooltips.js
src/utils/tippy/index.js

- feat: bump to 2.4.15-beta.10 && 修复 tooltip allowHTML 配置单词拼错的问题

feat: bump to 2.4.15-beta.10 && 修复 tooltip allowHTML 配置单词拼错的问题

---

package.json
src/directives/tooltips.js

- feat: bump to 2.4.15-beta.12 && 修复 tooltip allowHTML 配置单词拼错的问题

feat: bump to 2.4.15-beta.12 && 修复 tooltip allowHTML 配置单词拼错的问题

---

example/components/changelog/readme.md
src/directives/tooltips.js
src/utils/tippy/index.js

- bugfix: bump to 2.5.1 && 修复 tooltip allowHTML 配置单词拼错的问题

bugfix: bump to 2.5.1 && 修复 tooltip allowHTML 配置单词拼错的问题

---

example/components/changelog/readme.md
example/components/tooltips/example.vue
example/components/tooltips/readme.md
package.json
src/directives/tooltips.js
src/utils/tippy/index.js

feat: bump to 2.5.2

---

package.json
src/directives/tooltips.js
src/utils/tippy/index.js

- feat: bump to 2.4.15-beta.13 && tippy allowHTML 配置默认改为 true

feat: bump to 2.4.15-beta.13 && tippy allowHTML 配置默认改为 true

---

example/components/changelog/readme.md
example/index.html

- feat: bump to 2.5.2 && change document title

feat: bump to 2.5.2 && change document title

---

example/components/changelog/readme.md
example/components/time-picker/readme.md
package.json
src/components/date-picker/picker.vue

- feat: bump to 2.4.15-beta.14 && 修复 timepicker 编辑后，值没有更新的问题

feat: bump to 2.4.15-beta.14 && 修复 timepicker 编辑后，值没有更新的问题

---

example/components/changelog/readme.md
package.json
src/directives/tooltips.js

- feat: bump to 2.4.15-beta.15 && directives tooltips 的 allowHTML 默认配置改为 true

feat: bump to 2.4.15-beta.15 && directives tooltips 的 allowHTML 默认配置改为 true

---

example/components/changelog/readme.md
package.json
src/components/input/input.vue
src/components/table/table.vue

…e 为空的问题 && input 数字框输入特殊字符问题
- table 组件修复 setHeaderStyle 方法获取 bkTable 为空的问题
- input 数字框输入特殊字符问题，拼音问题

feat: bump to 2.4.15-beta.16

---

example/components/changelog/readme.md
package.json
src/components/input/input.vue

- feat: bump to 2.4.15-beta.17 && input 修复 locale 的引入问题

feat: bump to 2.4.15-beta.17 && input 修复 locale 的引入问题

---

example/components/changelog/readme.md
example/components/input/readme.md
package.json
src/components/input/input.vue

feat: bump to 2.5.3-beta.9 && input 组件非数字输入框输入问题

---

example/components/changelog/readme.md
package.json
src/components/input/input.vue

- feat: bump to 2.4.15-beta.18 && input 组件非数字输入框输入问题

feat: bump to 2.4.15-beta.18 && input 组件非数字输入框输入问题

---

package.json

- feat: bump to 2.5.3-beta.11 && 数字输入框输入 `-` 后失去焦点后，如果设置了最小值，值变为最小值，没有设置最小值，值变为 0

feat: bump to 2.5.3-beta.11 && 数字输入框输入 `-` 后失去焦点后，如果设置了最小值，值变为最小值，没有设置最小值，值变为 0

---

example/components/changelog/readme.md
package.json
src/components/input/input.vue

- feat: bump to 2.4.15-beta.19 && 数字输入框输入 `-` 后失去焦点后，如果设置了最小值，值变为最小值，没有设置最小值，值变为 0

feat: bump to 2.4.15-beta.19 && 数字输入框输入 `-` 后失去焦点后，如果设置了最小值，值变为最小值，没有设置最小值，值变为 0

---

example/components/changelog/readme.md
package.json
src/components/input/input.vue

- feat: bump to 2.5.3-beta.13 && 数字输入框粘贴非数字的情况处理

feat: bump to 2.5.3-beta.13 && 数字输入框粘贴非数字的情况处理

---

example/components/changelog/readme.md
package.json
src/components/input/input.vue

- feat: bump to 2.4.15-beta.21 && 数字输入框粘贴非数字的情况处理

feat: bump to 2.4.15-beta.21 && 数字输入框粘贴非数字的情况处理

---

example/components/changelog/readme.md
package.json

- feat: bump to 2.5.3-beta.14 && 版本更新明细业务组件 功能增强

feat: bump to 2.5.3-beta.14 && 版本更新明细业务组件 功能增强

---

example/components/table/readme.md
src/components/table/table-store.js

bugfix(table): clear filter method not working

---

example/components/changelog/readme.md
example/components/date-picker/readme.md
example/components/select/readme.md
example/components/tag-input/example.vue
example/components/tag-input/readme.md
src/components/tag-input/tag-input.vue

feat: bump to 2.5.3

---

example/components/version-detail/readme.md
src/components/version-detail/version-detail.vue

feat(version-detail): 支持指定默认选中的版本

---

example/components/changelog/readme.md
package.json

- feat: bump to 2.5.4-beta.1 && 版本更新明细业务组件 支持指定默认选中的版本

feat: bump to 2.5.4-beta.1 && 版本更新明细业务组件 支持指定默认选中的版本

---

example/components/changelog/readme.md
package.json

- feat: bump to 2.5.4-beta.2 && tag 组件 新增色块样式

feat: bump to 2.5.4-beta.2 && tag 组件 新增色块样式

---

src/components/big-tree/tree-item.vue
src/components/big-tree/tree-node.js
src/components/big-tree/tree.vue

feature(big-tree): 增加单独禁用checkbox选项

---

example/components/changelog/readme.md
package.json

- feat: bump to 2.5.4-beta.4 && big-tree: 增加单独禁用checkbox选项

feat: bump to 2.5.4-beta.4 && big-tree: 增加单独禁用checkbox选项

---

src/components/big-tree/tree.vue

bugfix(big-tree): 搜索时连线的计算问题

---

src/utils/tippy/popper.js

- bugfix: 去除tippy will-change影响

bugfix: 去除tippy will-change影响

---

example/components/changelog/readme.md

- feat: bump to 2.5.4-beta.8 && 去除 tippy will-change 影响

feat: bump to 2.5.4-beta.8 && 去除 tippy will-change 影响

---

src/components/select/select-tag.vue
src/components/tag-input/tag-input.vue
src/components/tag-input/tag-render.js

feat: select & taginput tag模式新增tooltips

---

example/components/changelog/readme.md
package.json

feat: bump to 2.5.4-beta.9

---

example/components/timeline/readme.md

chore(timeline): 文档中添加节点loading效果

---

example/components.config.js
example/components/changelog/readme.md
package.json
src/directives/tooltips.js
src/utils/tippy/index.js
src/utils/util.js

feat: bump to 2.5.4

---

example/index.html

feat: change document title

---

src/components/sideslider/sideslider.vue

bugfix(sideslide): 修复侧边栏宽度仅支持数字的问题 #399

---

src/utils/pop-manager.js

feat: 添加isMaskShown方法，用于检测当前页面遮罩是否弹出 #401

---

example/App.vue
example/components/changelog/readme.md
package.json
src/components/date-picker/panel/date.vue

feat: bump to 2.5.6-beta.2

---

example/components/changelog/readme.md
package.json
src/components/search-select/search-select.vue

- feat: bump to 2.5.6-beta.3
- fix #405

feat: bump to 2.5.6-beta.3 

---

example/components/tag-input/readme.md
src/components/tag-input/tag-input.vue

feat(tag-input): 添加动态列表的功能 #409

---

example/components/button/example.vue
example/components/button/readme.md
example/components/changelog/readme.md
example/components/install/readme.md
example/components/table/example.vue
package.json
single.html
src/components/table/table-layout.js
src/ui/button.css
src/ui/mixins/create-button.css

feat: bump to 2.5.6

---

package.json

- feat: update @blueking/magicbox-header

feat: update @blueking/magicbox-header

---

src/components/message/message.vue

feature(message): 支持自定义z-index

---

src/components/cascade/cascade.vue
src/components/cascade/caspanel.vue

bugfix(cascader): 修复filterable和checkany卡死的问题 #1071

---

example/components/search-select/readme.md
example/components/select/readme.md
src/components/search-select/search-select-menu.vue
src/components/search-select/search-select.vue
src/components/select/option.vue
src/components/select/select.vue
src/ui/search-select-menu.css
src/ui/select.css

feat: select & searchSelect新增checkbox模式

---

example/components.config.js
example/components/search-select/example.vue
example/components/search-select/readme.md
src/components/search-select/search-select.vue
src/ui/search-select-menu.css
src/ui/search-select.css

feat(search-select): 新增推荐搜索选择的功能

---

example/components/changelog/readme.md
example/components/message/readme.md
example/components/navigation/demo.vue
example/components/navigation/demo1.vue
example/components/navigation/readme.md
example/components/search-select/example.vue
example/components/search-select/readme.md
example/components/tooltips/readme.md
package.json

feat: bump to 2.5.7

---

example/components/changelog/readme.md
example/components/date-picker/readme.md
package.json
src/components/date-picker/base/month-table.vue
src/components/date-picker/base/year-table.vue
src/ui/form.css

feat: bump to 2.5.8-beta.1

---

example/components/changelog/readme.md
package.json
src/components/date-picker/panel/date-range.vue
src/components/date-picker/panel/date.vue

feat: bump to 2.5.8-beta.3

---

build/config.js
src/components/message/message.js

bugfix(message): message 自定义消息内容 VNode报错 #426

---

example/components/changelog/readme.md
package.json

feat: bump to 2.5.8-beta.5

---

src/components/message/message.vue
src/components/swiper/swiper.vue
src/components/table/table-layout.js

feat: 删除调试代码

---

package.json

feat: bump to 2.5.8-beta.7

---

example/components/select/readme.md

bugfix(select): 下拉列表滚动分页示例代码更新 #433

---

src/components/message/advanced.js
src/components/message/message.js
src/components/message/message.vue

feat(Message): 高阶模式支持多开 & 互斥模式

---

example/components/changelog/readme.md
package.json

feat: bump to 2.5.8-beta.8

---

example/components/changelog/readme.md
package.json
src/components/pagination/pagination.vue

feat: bump to 2.5.8-beta.9

---

src/components/message/message.js

fix:(Message): 高阶模式容器zIndex修复 #417

fix:(Message): 高阶模式容器zIndex修复 #417

---

example/components/changelog/readme.md
package.json

feat: bump to 2.5.8-beta.10

---

src/components/message/advanced.js

feature(Message): 高阶模式图钉增加取消快捷键 #417

---

example/components/changelog/readme.md
package.json

feat: bump to 2.5.8-beta.11

---

src/components/tab/tab.vue

bugfix: 修复tab组件type类型为card-tab一直抛warn问题

---

src/components/table/table-header.js
src/ui/table.css

feat(Table): Column resize style update
